<template>
  <v-chart class="chart" :option="option" />
</template>

<script lang="ts">
import { use } from "echarts/core";
import { BarChart } from "echarts/charts";
import {
  TitleComponent,
  GridComponent,
  TooltipComponent,
  LegendComponent,
} from "echarts/components";
import { CanvasRenderer } from "echarts/renderers";

import VChart, { THEME_KEY } from "vue-echarts";

use([
  TitleComponent,
  GridComponent,
  BarChart,
  CanvasRenderer,
  TooltipComponent,
  LegendComponent,
]);

export default {
  props: {
    chartData: {},
  },

  data(): any {
    return {
      option: null,
    };
  },

  watch: {
    chartData() {
      this.option = this.createChartOption();
    },
  },

  methods: {
    createChartOption() {
      const { labels, legend, series } = this.chartData;

      return {
        // title: {
        //   text: "Fees generated by category",
        // },
        tooltip: {
          trigger: "axis",
          axisPointer: {
            type: "none",
          },
        },
        legend,
        xAxis: {
          data: labels,
        },
        yAxis: {},
        series,
      };
    },
  },

  mounted() {
    this.option = this.createChartOption();
  },

  components: {
    VChart,
  },

  provide: {
    [THEME_KEY as keyof typeof THEME_KEY]: "dark",
  },
};
</script>
